name: Releases

on: 
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: tar -cvzf ./dist/file.tar.gz ./dist/bundle.js ./public/*
    - run: ls -li ./dist
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./dist/file.tar.gz