name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - run: tar -cvzf ./dist/test/file.tar.gz ./dist/bundle.js ./public/*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ./dist/test/file.tar.gz


# - run: |-
#       gzip bundle.js index.html asstets/ > thing.gz

      
      

    # - uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "thing.gz"