name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        artifacts: dist/bundle.js


# - run: |-
#       gzip bundle.js index.html asstets/ > thing.gz

      
      

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "thing.gz"